#!/usr/bin/env python3
"""
Script to update all mock data with Indian context names and rupee symbols
"""

import os
import re

# Indian names to replace foreign names
NAME_REPLACEMENTS = {
    'John Doe': 'Sara Sharma',
    'Sarah Jenkins': 'Priya Patel',
    'Michael Smith': 'Rahul Kumar',
    'Emily Johnson': 'Anjali Singh',
    'David Brown': 'Vikram Sharma',
    'Jessica Davis': 'Sunita Kumari',
    'James Wilson': 'Rajesh Kumar',
    'Jennifer Moore': 'Meena Devi',
    'Robert Taylor': 'Sanjay Kumar',
    'Lisa Anderson': 'Pooja Sharma',
    'William Thomas': 'Arun Kumar',
    'Mary Jackson': 'Kavita Sharma',
    'Richard White': 'Deepak Kumar',
    'Patricia Harris': 'Neha Sharma',
    'Charles Martin': 'Manoj Kumar',
    'Linda Thompson': 'Swati Sharma',
    'Joseph Garcia': 'Vijay Kumar',
    'Barbara Martinez': 'Rashmi Sharma',
    'Thomas Robinson': 'Anand Kumar',
    'Susan Clark': 'Divya Sharma',
    'Christopher Lewis': 'Rohit Kumar',
    'Nancy Walker': 'Shweta Sharma',
    'Daniel Hall': 'Ajay Kumar',
    'Karen Allen': 'Rekha Sharma',
    'Matthew Young': 'Suresh Kumar',
    'Betty King': 'Madhuri Sharma',
    'Anthony Wright': 'Vinod Kumar',
    'Helen Lopez': 'Kiran Sharma',
    'Mark Hill': 'Mahesh Kumar',
    'Sandra Scott': 'Anita Sharma',
    'Donald Green': 'Ramesh Kumar',
    'Ashley Baker': 'Lata Sharma',
    'Paul Adams': 'Rahul Kumar Sharma',
    'Kimberly Nelson': 'Priya Kumari Patel',
    'Steven Carter': 'Amit Kumar Singh',
    'Donna Mitchell': 'Anjali Kumari Singh',
    'George Perez': 'Vikram Kumar Gupta',
    'Carol Roberts': 'Sunita Kumari Gupta',
    'Kenneth Turner': 'Rajesh Kumar Gupta',
    'Michelle Phillips': 'Meena Kumari Gupta',
    'Edward Campbell': 'Sanjay Kumar Gupta',
    'Laura Parker': 'Pooja Kumari Gupta',
    'Ronald Evans': 'Arun Kumar Gupta',
    'Sarah Edwards': 'Kavita Kumari Gupta',
    'Kevin Collins': 'Deepak Kumar Gupta',
    'Brian Stewart': 'Manoj Kumar Gupta',
    'Judith Sanchez': 'Swati Kumari Gupta',
    'Timothy Morris': 'Vijay Kumar Gupta',
    'Deborah Rogers': 'Rashmi Kumari Gupta',
    'Jason Reed': 'Anand Kumar Gupta',
    'Sharon Cook': 'Divya Kumari Gupta',
    'Jeffrey Morgan': 'Rohit Kumar Gupta',
    'Cynthia Bell': 'Shweta Kumari Gupta',
    'Frank Murphy': 'Ajay Kumar Gupta',
    'Maria Bailey': 'Rekha Kumari Gupta',
    'Ryan Rivera': 'Suresh Kumar Gupta',
    'Lisa Cooper': 'Madhuri Kumari Gupta',
    'Eric Richardson': 'Vinod Kumar Gupta',
    'Nancy Cox': 'Kiran Kumari Gupta',
    'Stephen Howard': 'Mahesh Kumar Gupta',
    'Helen Ward': 'Anita Kumari Gupta',
    'Larry Torres': 'Ramesh Kumar Gupta',
    'Virginia Peterson': 'Lata Kumari Gupta',
    'Scott Gray': 'Rahul Kumar Sharma',
    'Brenda Ramirez': 'Priya Kumari Sharma',
    'Bradley James': 'Amit Kumar Sharma',
    'Pamela Watson': 'Anjali Kumari Sharma',
    'Samuel Brooks': 'Vikram Kumar Sharma',
    'Katherine Kelly': 'Sunita Kumari Sharma',
    'Henry Sanders': 'Rajesh Kumar Sharma',
    'Christine Price': 'Meena Kumari Sharma',
    'Jack Bennett': 'Sanjay Kumar Sharma',
    'Samantha Wood': 'Pooja Kumari Sharma',
    'Johnny Barnes': 'Arun Kumar Sharma',
    'Deborah Ross': 'Kavita Kumari Sharma',
    'Dana Henderson': 'Deepak Kumar Sharma',
    'Catherine Coleman': 'Manoj Kumar Sharma',
    'Joseph Perry': 'Swati Kumar Sharma',
    'Patrick Powell': 'Vijay Kumar Sharma',
    'Catherine Long': 'Rashmi Kumari Sharma',
    'Peter Patterson': 'Anand Kumar Sharma',
    'Angela Hughes': 'Divya Kumar Sharma',
    'Chris Flores': 'Rohit Kumar Sharma',
    'Martha Washington': 'Shweta Kumar Sharma',
    'Alexander Butler': 'Ajay Kumar Sharma',
    'Sharon Simmons': 'Rekha Kumar Sharma',
    'George Foster': 'Suresh Kumar Sharma',
    'Frances Gonzales': 'Madhuri Kumar Sharma',
    'Edward Bryant': 'Vinod Kumar Sharma',
    'Amy Alexander': 'Kiran Kumar Sharma',
    'Walter Russell': 'Mahesh Kumar Sharma',
    'Brenda Griffin': 'Anita Kumar Sharma',
    'Diane Diaz': 'Lata Kumar Sharma',
    'Samuel Hayes': 'Rahul Kumar Singh',
    'Rachel Myers': 'Priya Kumari Singh',
    'Earl Ford': 'Amit Kumar Singh',
    'Todd Hamilton': 'Anjali Kumar Singh',
    'Nicole Graham': 'Sunita Kumar Singh',
    'Nathan Sullivan': 'Rajesh Kumar Singh',
    'Kelly Wallace': 'Meena Kumar Singh',
    'Chris Woods': 'Sanjay Kumar Singh',
    'Tracy Cole': 'Pooja Kumar Singh',
    'Peter West': 'Arun Kumar Singh',
    'Cynthia Owens': 'Kavita Kumar Singh',
    'Harry Hunt': 'Deepak Kumar Singh',
    'Lori Mason': 'Manoj Kumar Singh',
    'Jeffrey Walters': 'Swati Kumar Singh',
    'Kenneth Payne': 'Vijay Kumar Singh',
    'Virginia Frazier': 'Rashmi Kumar Singh',
    'Justin Holmes': 'Anand Kumar Singh',
    'Katherine Mills': 'Divya Kumar Singh',
    'Randy Butler': 'Rohit Kumar Singh',
    'Andrea Carpenter': 'Shweta Kumar Singh',
    'Lawrence Lawrence': 'Ajay Kumar Singh',
    'Megan Lawrence': 'Rekha Kumar Singh',
    'Keith Elliott': 'Suresh Kumar Singh',
    'Stephanie Cruz': 'Madhuri Kumar Singh',
    'Russell Hughes': 'Vinod Kumar Singh',
    'Laura Jordan': 'Kiran Kumar Singh',
    'Benjamin Powell': 'Mahesh Kumar Singh',
    'Pamela Jenkins': 'Anita Kumar Singh',
    'Gregory Perry': 'Ramesh Kumar Singh',
    'Christine Barnes': 'Lata Kumar Singh',
    'Samuel Fisher': 'Rahul Kumar Mishra',
    'Victoria Henderson': 'Priya Kumari Mishra',
    'Raymond Kelley': 'Amit Kumar Mishra',
    'Jacqueline Franklin': 'Anjali Kumar Mishra',
    'Frank Lynch': 'Vikram Kumar Mishra',
    'Janet Gross': 'Sunita Kumar Mishra',
    'Patrick Boyd': 'Rajesh Kumar Mishra',
    'Diane Payne': 'Meena Kumar Mishra',
    'Ryan Baker': 'Sanjay Kumar Mishra',
    'Joyce Hopkins': 'Pooja Kumar Mishra',
    'Joshua Perry': 'Arun Kumar Mishra',
    'Nicole Ward': 'Kavita Kumar Mishra',
    'Bruce Ramirez': 'Deepak Kumar Mishra',
    'Ashley James': 'Manoj Kumar Mishra',
    'Adam Watkins': 'Swati Kumar Mishra',
    'Elizabeth Ellis': 'Vijay Kumar Mishra',
    'Jose Owens': 'Rashmi Kumar Mishra',
    'Thomas Reynolds': 'Anand Kumar Mishra',
    'Cynthia Fisher': 'Divya Kumar Mishra',
    'David Hayes': 'Rohit Kumar Mishra',
    'Patrick Nichols': 'Shweta Kumar Mishra',
    'Ryan Murray': 'Ajay Kumar Mishra',
    'Michelle Freeman': 'Rekha Kumar Mishra',
    'Kevin Lloyd': 'Suresh Kumar Mishra',
    'Jason Gomez': 'Madhuri Kumar Mishra',
    'Frank Rogers': 'Vinod Kumar Mishra',
    'Timothy Peterson': 'Kiran Kumar Mishra',
    'Jessica Cooper': 'Mahesh Kumar Mishra',
    'Justin Reed': 'Anita Kumar Mishra',
    'Brian Bailey': 'Ramesh Kumar Mishra',
    'Christopher Bell': 'Lata Kumar Mishra',
    'Daniel Murphy': 'Rahul Kumar Reddy',
    'Matthew Bailey': 'Priya Kumari Reddy',
    'Anthony Cooper': 'Amit Kumar Reddy',
    'Paul Richardson': 'Anjali Kumar Reddy',
    'Mark Cox': 'Vikram Kumar Reddy',
    'Steven Howard': 'Sunita Kumar Reddy',
    'Kevin Ward': 'Rajesh Kumar Reddy',
    'Thomas Torres': 'Meena Kumar Reddy',
    'Joseph Peterson': 'Sanjay Kumar Reddy',
    'Charles Gray': 'Pooja Kumar Reddy',
    'Robert Ramirez': 'Arun Kumar Reddy',
    'Patrick James': 'Kavita Kumar Reddy',
    'Christopher Brooks': 'Deepak Kumar Reddy',
    'Daniel Kelly': 'Manoj Kumar Reddy',
    'Paul Sanders': 'Swati Kumar Reddy',
    'Mark Price': 'Vijay Kumar Reddy',
    'Donald Bennett': 'Rashmi Kumar Reddy',
    'George Wood': 'Anand Kumar Reddy',
    'Ryan Barnes': 'Divya Kumar Reddy',
    'Edward Henderson': 'Rohit Kumar Reddy',
    'Joseph Coleman': 'Shweta Kumar Reddy',
    'Thomas Jenkins': 'Ajay Kumar Reddy',
    'Ronald Perry': 'Rekha Kumar Reddy',
    'Kevin Powell': 'Suresh Kumar Reddy',
    'Brian Long': 'Madhuri Kumar Reddy',
    'Scott Patterson': 'Vinod Kumar Reddy',
    'Frank Hughes': 'Kiran Kumar Reddy',
    'Jason Flores': 'Mahesh Kumar Reddy',
    'Larry Washington': 'Anita Kumar Reddy',
    'Jeffrey Butler': 'Ramesh Kumar Reddy',
    'Steven Simmons': 'Lata Kumar Reddy',
    'George Foster': 'Rahul Kumar Nair',
    'Ryan Gonzales': 'Priya Kumari Nair',
    'Christopher Foster': 'Amit Kumar Nair',
    'Edward Hunter': 'Anjali Kumar Nair',
    'Samuel Torres': 'Vikram Kumar Nair',
    'Patrick Peterson': 'Sunita Kumar Nair',
    'Frank Gray': 'Rajesh Kumar Nair',
    'Daniel Ramirez': 'Meena Kumar Nair',
    'Ryan James': 'Sanjay Kumar Nair',
    'Brian Watson': 'Pooja Kumar Nair',
    'Kevin Brooks': 'Arun Kumar Nair',
    'Joseph Kelly': 'Kavita Kumar Nair',
    'Thomas Sanders': 'Deepak Kumar Nair',
    'Christopher Price': 'Manoj Kumar Nair',
    'Jason Baker': 'Swati Kumar Nair',
    'David Perez': 'Vijay Kumar Nair',
    'Jeffrey Russell': 'Rashmi Kumar Nair',
    'Ryan Collins': 'Anand Kumar Nair',
    'Steven Edwards': 'Divya Kumar Nair',
    'Timothy Stewart': 'Rohit Kumar Nair',
    'Frank Sanchez': 'Shweta Kumar Nair',
    'William Morris': 'Ajay Kumar Nair',
    'Joseph Rogers': 'Rekha Kumar Nair',
    'David Reed': 'Suresh Kumar Nair',
    'Richard Cook': 'Madhuri Kumar Nair',
    'Christopher Morgan': 'Vinod Kumar Nair',
    'Daniel Bell': 'Kiran Kumar Nair',
    'Paul Murphy': 'Mahesh Kumar Nair',
    'Mark Bailey': 'Anita Kumar Nair',
    'Steven Rivera': 'Ramesh Kumar Nair',
    'George Cooper': 'Lata Kumar Nair',
    'Ryan Richardson': 'Rahul Kumar Iyer',
    'Frank Cox': 'Priya Kumari Iyer',
    'Kevin Ward': 'Amit Kumar Iyer',
    'Thomas Torres': 'Anjali Kumar Iyer',
    'Joseph Peterson': 'Vikram Kumar Iyer',
    'David Campbell': 'Sunita Kumar Iyer',
    'Christopher Roberts': 'Rajesh Kumar Iyer',
    'Daniel Turner': 'Meena Kumar Iyer',
    'Ryan Phillips': 'Sanjay Kumar Iyer',
    'Brian Campbell': 'Pooja Kumar Iyer',
    'Jason Parker': 'Arun Kumar Iyer',
    'Matthew Evans': 'Kavita Kumar Iyer',
    'Joseph Edwards': 'Deepak Kumar Iyer',
    'Thomas Collins': 'Manoj Kumar Iyer',
    'Frank Stewart': 'Swati Kumar Iyer',
    'David Sanchez': 'Vijay Kumar Iyer',
    'Christopher Morris': 'Rashmi Kumar Iyer',
    'Ryan Rogers': 'Anand Kumar Iyer',
    'Steven Reed': 'Divya Kumar Iyer',
    'Kevin Cook': 'Rohit Kumar Iyer',
    'Joseph Morgan': 'Shweta Kumar Iyer',
    'Daniel Bell': 'Ajay Kumar Iyer',
    'Patrick Murphy': 'Rekha Kumar Iyer',
    'Frank Bailey': 'Suresh Kumar Iyer',
    'Christopher Rivera': 'Madhuri Kumar Iyer',
    'Ryan Cooper': 'Vinod Kumar Iyer',
    'Thomas Richardson': 'Kiran Kumar Iyer',
    'Jason Cox': 'Mahesh Kumar Iyer',
    'David Ward': 'Anita Kumar Iyer',
    'Joseph Torres': 'Ramesh Kumar Iyer',
    'Kevin Peterson': 'Lata Kumar Iyer',
    'Brian White': 'Rahul Kumar Menon',
    'Frank Harris': 'Priya Kumari Menon',
    'Christopher Martin': 'Amit Kumar Menon',
    'Daniel Thompson': 'Anjali Kumar Menon',
    'Ryan Martinez': 'Vikram Kumar Menon',
    'Thomas Garcia': 'Sunita Kumar Menon',
    'Joseph Robinson': 'Rajesh Kumar Menon',
    'David Clark': 'Meena Kumar Menon',
    'Christopher Rodriguez': 'Sanjay Kumar Menon',
    'Frank Lewis': 'Pooja Kumar Menon',
    'Ryan Lee': 'Arun Kumar Menon',
    'Daniel Walker': 'Kavita Kumar Menon',
    'Joseph Hall': 'Deepak Kumar Menon',
    'Thomas Allen': 'Manoj Kumar Menon',
    'Brian Young': 'Swati Kumar Menon',
    'Kevin Hernandez': 'Vijay Kumar Menon',
    'Frank King': 'Rashmi Kumar Menon',
    'Christopher Wright': 'Anand Kumar Menon',
    'Ryan Lopez': 'Divya Kumar Menon',
    'Joseph Hill': 'Rohit Kumar Menon',
    'Daniel Scott': 'Shweta Kumar Menon',
    'Thomas Green': 'Ajay Kumar Menon',
    'Frank Adams': 'Rekha Kumar Menon',
    'Christopher Baker': 'Suresh Kumar Menon',
    'Ryan Nelson': 'Madhuri Kumar Menon',
    'Joseph Carter': 'Vinod Kumar Menon',
    'David Mitchell': 'Kiran Kumar Menon',
    'Kevin Perez': 'Mahesh Kumar Menon',
    'Brian Roberts': 'Anita Kumar Menon',
    'Frank Turner': 'Ramesh Kumar Menon',
    'Christopher Phillips': 'Lata Kumar Menon',
    'Ryan Campbell': 'Rahul Kumar Pillai',
    'Joseph Parker': 'Priya Kumari Pillai',
    'Daniel Evans': 'Amit Kumar Pillai',
    'Thomas Edwards': 'Anjali Kumar Pillai',
    'Frank Collins': 'Vikram Kumar Pillai',
    'Christopher Stewart': 'Sunita Kumar Pillai',
    'Ryan Sanchez': 'Rajesh Kumar Pillai',
    'Joseph Morris': 'Meena Kumar Pillai',
    'David Rogers': 'Sanjay Kumar Pillai',
    'Kevin Reed': 'Pooja Kumar Pillai',
    'Brian Cook': 'Arun Kumar Pillai',
    'Frank Morgan': 'Kavita Kumar Pillai',
    'Christopher Bell': 'Deepak Kumar Pillai',
    'Ryan Murphy': 'Manoj Kumar Pillai',
    'Joseph Bailey': 'Swati Kumar Pillai',
    'Daniel Rivera': 'Vijay Kumar Pillai',
    'Thomas Cooper': 'Rashmi Kumar Pillai',
    'Frank Richardson': 'Anand Kumar Pillai',
    'Christopher Cox': 'Divya Kumar Pillai',
    'Ryan Howard': 'Rohit Kumar Pillai',
    'Joseph Ward': 'Shweta Kumar Pillai',
    'David Torres': 'Ajay Kumar Pillai',
    'Kevin Peterson': 'Rekha Kumar Pillai',
    'Brian Gray': 'Suresh Kumar Pillai',
    'Frank Ramirez': 'Madhuri Kumar Pillai',
    'Christopher James': 'Vinod Kumar Pillai',
    'Ryan Watson': 'Kiran Kumar Pillai',
    'Joseph Brooks': 'Mahesh Kumar Pillai',
    'Daniel Kelly': 'Anita Kumar Pillai',
    'Thomas Sanders': 'Ramesh Kumar Pillai',
    'Frank Price': 'Lata Kumar Pillai',
    'Christopher Bennett': 'Rahul Kumar Rao',
    'Ryan Wood': 'Priya Kumari Rao',
    'Joseph Barnes': 'Amit Kumar Rao',
    'David Ross': 'Anjali Kumar Rao',
    'Kevin Henderson': 'Vikram Kumar Rao',
    'Brian Coleman': 'Sunita Kumar Rao',
    'Frank Jenkins': 'Rajesh Kumar Rao',
    'Christopher Perry': 'Meena Kumar Rao',
    'Ryan Powell': 'Sanjay Kumar Rao',
    'Joseph Long': 'Pooja Kumar Rao',
    'Daniel Patterson': 'Arun Kumar Rao',
    'Thomas Flores': 'Kavita Kumar Rao',
    'Frank Washington': 'Deepak Kumar Rao',
    'Christopher Cheney': 'Manoj Kumar Rao',
    'Ryan Simmons': 'Swati Kumar Rao',
    'Joseph Frost': 'Vijay Kumar Rao',
    'David Woods': 'Rashmi Kumar Rao',
    'Kevin Bryant': 'Anand Kumar Rao',
    'Brian Alexander': 'Divya Kumar Rao',
    'Frank Meyer': 'Rohit Kumar Rao',
    'Christopher Rice': 'Shweta Kumar Rao',
    'Ryan Ellis': 'Ajay Kumar Rao',
    'Joseph Harrison': 'Rekha Kumar Rao',
    'Daniel Gibson': 'Suresh Kumar Rao',
    'Thomas Mueller': 'Madhuri Kumar Rao',
    'Frank Schultz': 'Vinod Kumar Rao',
    'Christopher Johnston': 'Kiran Kumar Rao',
    'Ryan Frank': 'Mahesh Kumar Rao',
    'Brian Waters': 'Anita Kumar Rao',
    'David Schmidt': 'Ramesh Kumar Rao',
    'Kevin Zimmerman': 'Lata Kumar Rao',
    'Joseph Graham': 'Rahul Kumar Chatterjee',
    'Christopher Ryan': 'Priya Kumari Chatterjee',
    'Daniel Nichols': 'Amit Kumar Chatterjee',
    'Thomas Butler': 'Anjali Kumar Chatterjee',
    'Frank Diaz': 'Vikram Kumar Chatterjee',
    'Ryan Hayes': 'Sunita Kumar Chatterjee',
    'Brian Cruz': 'Rajesh Kumar Chatterjee',
    'David King': 'Meena Kumar Chatterjee',
    'Kevin Scott': 'Sanjay Kumar Chatterjee',
    'Joseph Green': 'Pooja Kumar Chatterjee',
    'Christopher Baker': 'Arun Kumar Chatterjee',
    'Ryan Thompson': 'Kavita Kumar Chatterjee',
    'Daniel White': 'Deepak Kumar Chatterjee',
    'Thomas Harris': 'Manoj Kumar Chatterjee',
    'Frank Martin': 'Swati Kumar Chatterjee',
    'Christopher Thompson': 'Vijay Kumar Chatterjee',
    'Ryan Garcia': 'Rashmi Kumar Chatterjee',
    'Joseph Martinez': 'Anand Kumar Chatterjee',
    'David Robinson': 'Divya Kumar Chatterjee',
    'Kevin Clark': 'Rohit Kumar Chatterjee',
    'Brian Rodriguez': 'Shweta Kumar Chatterjee',
    'Frank Lewis': 'Ajay Kumar Chatterjee',
    'Christopher Lee': 'Rekha Kumar Chatterjee',
    'Ryan Walker': 'Suresh Kumar Chatterjee',
    'Joseph Hall': 'Madhuri Kumar Chatterjee',
    'Daniel Allen': 'Vinod Kumar Chatterjee',
    'Thomas Young': 'Kiran Kumar Chatterjee',
    'Frank Hernandez': 'Mahesh Kumar Chatterjee',
    'Christopher Wright': 'Anita Kumar Chatterjee',
    'Ryan Lopez': 'Ramesh Kumar Chatterjee',
    'Joseph Hill': 'Lata Kumar Chatterjee',
    'David Scott': 'Rahul Kumar Mukherjee',
    'Kevin Green': 'Priya Kumari Mukherjee',
    'Brian Adams': 'Amit Kumar Mukherjee',
    'Frank Baker': 'Anjali Kumar Mukherjee',
    'Christopher Nelson': 'Vikram Kumar Mukherjee',
    'Ryan Mitchell': 'Sunita Kumar Mukherjee',
    'Joseph Perez': 'Rajesh Kumar Mukherjee',
    'Daniel Roberts': 'Meena Kumar Mukherjee',
    'Thomas Turner': 'Sanjay Kumar Mukherjee',
    'Frank Phillips': 'Pooja Kumar Mukherjee',
    'Christopher Campbell': 'Arun Kumar Mukherjee',
    'Ryan Parker': 'Kavita Kumar Mukherjee',
    'Joseph Evans': 'Deepak Kumar Mukherjee',
    'David Edwards': 'Manoj Kumar Mukherjee',
    'Kevin Collins': 'Swati Kumar Mukherjee',
    'Brian Stewart': 'Vijay Kumar Mukherjee',
    'Frank Sanchez': 'Rashmi Kumar Mukherjee',
    'Christopher Morris': 'Anand Kumar Mukherjee',
    'Ryan Rogers': 'Divya Kumar Mukherjee',
    'Joseph Reed': 'Rohit Kumar Mukherjee',
    'Daniel Cook': 'Shweta Kumar Mukherjee',
    'Thomas Morgan': 'Ajay Kumar Mukherjee',
    'Frank Bell': 'Rekha Kumar Mukherjee',
    'Christopher Murphy': 'Suresh Kumar Mukherjee',
    'Ryan Bailey': 'Madhuri Kumar Mukherjee',
    'Joseph Rivera': 'Vinod Kumar Mukherjee',
    'David Cooper': 'Kiran Kumar Mukherjee',
    'Kevin Richardson': 'Mahesh Kumar Mukherjee',
    'Brian Cox': 'Anita Kumar Mukherjee',
    'Frank Howard': 'Ramesh Kumar Mukherjee',
    'Christopher Ward': 'Lata Kumar Mukherjee',
    'Ryan Torres': 'Rahul Kumar Ghosh',
    'Joseph Peterson': 'Priya Kumari Ghosh',
    'Daniel Gray': 'Amit Kumar Ghosh',
    'Thomas Ramirez': 'Anjali Kumar Ghosh',
    'Frank James': 'Vikram Kumar Ghosh',
    'Christopher Brooks': 'Sunita Kumar Ghosh',
    'Ryan Kelly': 'Rajesh Kumar Ghosh',
    'Joseph Sanders': 'Meena Kumar Ghosh',
    'David Price': 'Sanjay Kumar Ghosh',
    'Kevin Bennett': 'Pooja Kumar Ghosh',
    'Brian Wood': 'Arun Kumar Ghosh',
    'Frank Barnes': 'Kavita Kumar Ghosh',
    'Christopher Ross': 'Deepak Kumar Ghosh',
    'Ryan Henderson': 'Manoj Kumar Ghosh',
    'Joseph Coleman': 'Swati Kumar Ghosh',
    'Daniel Jenkins': 'Vijay Kumar Ghosh',
    'Thomas Perry': 'Rashmi Kumar Ghosh',
    'Frank Powell': 'Anand Kumar Ghosh',
    'Christopher Long': 'Divya Kumar Ghosh',
    'Ryan Patterson': 'Rohit Kumar Ghosh',
    'Joseph Hughes': 'Shweta Kumar Ghosh',
    'David Flores': 'Ajay Kumar Ghosh',
    'Kevin Washington': 'Rekha Kumar Ghosh',
    'Brian Butler': 'Suresh Kumar Ghosh',
    'Frank Simmons': 'Madhuri Kumar Ghosh',
    'Christopher Foster': 'Vinod Kumar Ghosh',
    'Ryan Gonzales': 'Kiran Kumar Ghosh',
    'Joseph Alexander': 'Mahesh Kumar Ghosh',
    'Daniel Russell': 'Anita Kumar Ghosh',
    'Thomas Griffin': 'Ramesh Kumar Ghosh',
    'Frank Diaz': 'Lata Kumar Ghosh',
    'Christopher Hayes': 'Rahul Kumar Das',
    'Ryan Myers': 'Priya Kumari Das',
    'Joseph Ford': 'Amit Kumar Das',
    'David Hamilton': 'Anjali Kumar Das',
    'Kevin Palmer': 'Vikram Kumar Das',
    'Brian Harvey': 'Sunita Kumar Das',
    'Frank Crawford': 'Rajesh Kumar Das',
    'Christopher Gordon': 'Meena Kumar Das',
    'Ryan Shaw': 'Sanjay Kumar Das',
    'Joseph Snyder': 'Pooja Kumar Das',
    'Daniel Rice': 'Arun Kumar Das',
    'Thomas Coleman': 'Kavita Kumar Das',
    'Frank Jenkins': 'Deepak Kumar Das',
    'Christopher Perry': 'Manoj Kumar Das',
    'Ryan Barnes': 'Swati Kumar Das',
    'Joseph Fisher': 'Vijay Kumar Das',
    'David Cook': 'Rashmi Kumar Das',
    'Kevin Bailey': 'Anand Kumar Das',
    'Brian Cooper': 'Divya Kumar Das',
    'Frank Richardson': 'Rohit Kumar Das',
    'Christopher Cox': 'Shweta Kumar Das',
    'Ryan Howard': 'Ajay Kumar Das',
    'Joseph Ward': 'Rekha Kumar Das',
    'Daniel Torres': 'Suresh Kumar Das',
    'Thomas Peterson': 'Madhuri Kumar Das',
    'Frank Gray': 'Vinod Kumar Das',
    'Christopher Ramirez': 'Kiran Kumar Das',
    'Ryan James': 'Mahesh Kumar Das',
    'Brian Watson': 'Anita Kumar Das',
    'David Brooks': 'Ramesh Kumar Das',
    'Kevin Kelly': 'Lata Kumar Das',
    'Joseph Sanders': 'Rahul Kumar Sen',
    'Christopher Price': 'Priya Kumari Sen',
    'Daniel Bennett': 'Amit Kumar Sen',
    'Thomas Wood': 'Anjali Kumar Sen',
    'Frank Barnes': 'Vikram Kumar Sen',
    'Ryan Ross': 'Sunita Kumar Sen',
    'Joseph Henderson': 'Rajesh Kumar Sen',
    'David Coleman': 'Meena Kumar Sen',
    'Kevin Jenkins': 'Sanjay Kumar Sen',
    'Brian Perry': 'Pooja Kumar Sen',
    'Frank Powell': 'Arun Kumar Sen',
    'Christopher Long': 'Kavita Kumar Sen',
    'Ryan Patterson': 'Deepak Kumar Sen',
    'Joseph Hughes': 'Manoj Kumar Sen',
    'Daniel Flores': 'Swati Kumar Sen',
    'Thomas Washington': 'Vijay Kumar Sen',
    'Frank Butler': 'Rashmi Kumar Sen',
    'Christopher Simmons': 'Anand Kumar Sen',
    'Ryan Foster': 'Divya Kumar Sen',
    'Joseph Gonzales': 'Rohit Kumar Sen',
    'David Alexander': 'Shweta Kumar Sen',
    'Kevin Russell': 'Ajay Kumar Sen',
    'Brian Griffin': 'Rekha Kumar Sen',
    'Frank Diaz': 'Suresh Kumar Sen',
    'Christopher Hayes': 'Madhuri Kumar Sen',
    'Ryan Myers': 'Vinod Kumar Sen',
    'Joseph Ford': 'Kiran Kumar Sen',
    'Daniel Hamilton': 'Mahesh Kumar Sen',
    'Thomas Palmer': 'Anita Kumar Sen',
    'Frank Harvey': 'Ramesh Kumar Sen',
    'Christopher Crawford': 'Lata Kumar Sen',
    'Ryan Gordon': 'Rahul Kumar Bose',
    'Joseph Shaw': 'Priya Kumari Bose',
    'David Snyder': 'Amit Kumar Bose',
    'Kevin Rice': 'Anjali Kumar Bose',
    'Brian Coleman': 'Vikram Kumar Bose',
    'Frank Jenkins': 'Sunita Kumar Bose',
    'Christopher Perry': 'Rajesh Kumar Bose',
    'Ryan Barnes': 'Meena Kumar Bose',
    'Joseph Fisher': 'Sanjay Kumar Bose',
    'Daniel Cook': 'Pooja Kumar Bose',
    'Thomas Bailey': 'Arun Kumar Bose',
    'Frank Cooper': 'Kavita Kumar Bose',
    'Christopher Richardson': 'Deepak Kumar Bose',
    'Ryan Cox': 'Manoj Kumar Bose',
    'Joseph Howard': 'Swati Kumar Bose',
    'David Ward': 'Vijay Kumar Bose',
    'Kevin Torres': 'Rashmi Kumar Bose',
    'Brian Peterson': 'Anand Kumar Bose',
    'Frank Gray': 'Divya Kumar Bose',
    'Christopher Ramirez': 'Rohit Kumar Bose',
    'Ryan James': 'Shweta Kumar Bose',
    'Joseph Brooks': 'Ajay Kumar Bose',
    'Daniel Kelly': 'Rekha Kumar Bose',
    'Thomas Sanders': 'Suresh Kumar Bose',
    'Frank Price': 'Madhuri Kumar Bose',
    'Christopher Bennett': 'Vinod Kumar Bose',
    'Ryan Wood': 'Kiran Kumar Bose',
    'Joseph Barnes': 'Mahesh Kumar Bose',
    'David Ross': 'Anita Kumar Bose',
    'Kevin Henderson': 'Ramesh Kumar Bose',
    'Brian Coleman': 'Lata Kumar Bose',
    'Frank Jenkins': 'Rahul Kumar Sharma',
    'Christopher Perry': 'Priya Kumari Sharma',
    'Ryan Powell': 'Amit Kumar Sharma',
    'Joseph Long': 'Anjali Kumar Sharma',
    'Daniel Patterson': 'Vikram Kumar Sharma',
    'Thomas Flores': 'Sunita Kumar Sharma',
    'Frank Washington': 'Rajesh Kumar Sharma',
    'Christopher Cheney': 'Manoj Kumar Sharma',
    'Ryan Simmons': 'Swati Kumar Sharma',
    'Joseph Frost': 'Vijay Kumar Sharma',
    'David Woods': 'Rashmi Kumar Sharma',
    'Kevin Bryant': 'Anand Kumar Sharma',
    'Brian Alexander': 'Divya Kumar Sharma',
    'Frank Meyer': 'Rohit Kumar Sharma',
    'Christopher Rice': 'Shweta Kumar Sharma',
    'Ryan Ellis': 'Ajay Kumar Sharma',
    'Joseph Harrison': 'Rekha Kumar Sharma',
    'Daniel Gibson': 'Suresh Kumar Sharma',
    'Thomas Mueller': 'Madhuri Kumar Sharma',
    'Frank Schultz': 'Vinod Kumar Sharma',
    'Christopher Johnston': 'Kiran Kumar Sharma',
    'Ryan Frank': 'Mahesh Kumar Sharma',
    'Brian Waters': 'Anita Kumar Sharma',
    'David Schmidt': 'Ramesh Kumar Sharma',
    'Kevin Zimmerman': 'Lata Kumar Sharma'
}

def update_file_content(file_path, content):
    """Update file with new content"""
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated: {file_path}")
        return True
    except Exception as e:
        print(f"Error updating {file_path}: {e}")
        return False

def process_file(file_path):
    """Process a single file to replace names and currency symbols"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        
        # Replace foreign names with Indian names
        for foreign_name, indian_name in NAME_REPLACEMENTS.items():
            content = content.replace(foreign_name, indian_name)
        
        # Replace dollar signs with rupee symbols
        content = re.sub(r'\$', 'Rs.', content)
        content = re.sub(r'\$([0-9,]+)', r'Rs.\1', content)
        content = re.sub(r'dollar', 'rupee', content, flags=re.IGNORECASE)
        content = re.sub(r'Dollar', 'Rupee', content)
        
        # Replace USD with INR
        content = re.sub(r'USD', 'INR', content)
        content = re.sub(r'usd', 'inr', content)
        
        # Replace email domains with Indian context
        content = re.sub(r'@gmail\.com', '@gmail.com', content)
        content = re.sub(r'@yahoo\.com', '@gmail.com', content)
        content = re.sub(r'@hotmail\.com', '@gmail.com', content)
        content = re.sub(r'@outlook\.com', '@gmail.com', content)
        
        # Only write if content changed
        if content != original_content:
            update_file_content(file_path, content)
            return True
        else:
            print(f"No changes needed: {file_path}")
            return False
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return False

def main():
    """Main function to process all relevant files"""
    base_dir = "/Volumes/DrSmit/AntiGravity/project2026/MIT/v1"
    
    # Files to process
    files_to_process = [
        "src/app/login/page.tsx",
        "src/app/customer/dashboard/page.tsx",
        "src/app/insurer/dashboard/page.tsx",
        "src/app/insurance/health/page.tsx",
        "src/app/insurance/auto/page.tsx",
        "src/app/insurance/life/page.tsx",
        "src/app/insurance/corporate/page.tsx",
        "src/app/submit/page.tsx",
        "src/app/page.tsx",
        "backend/indian_seed_data.py",
        "backend/postgres_setup.py"
    ]
    
    print("Starting Indian context update...")
    print("=" * 50)
    
    updated_files = 0
    total_files = 0
    
    for file_path in files_to_process:
        full_path = os.path.join(base_dir, file_path)
        if os.path.exists(full_path):
            total_files += 1
            if process_file(full_path):
                updated_files += 1
        else:
            print(f"File not found: {full_path}")
    
    print("=" * 50)
    print(f"Processed {total_files} files")
    print(f"Updated {updated_files} files")
    print("Indian context update completed!")

if __name__ == "__main__":
    main()
